map_roles:
  workers_roles:
    - "{{ worker_iam_role_arn }}"
  system_masters:
    - "arn:aws:iam::111111111111:role/admin-role"
map_users:
  system_masters:
    - arn: "arn:aws:iam::111111111111:user/clusters-admin"
      name: "clusters.admin"
