apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: "arn:aws:iam::740781822140:role/patologia-clinica-lims-default-workers"
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: "arn:aws:iam::740781822140:role/patologia-clinica-lims-default-workers"
      username: "admin:{{SessionName}}"
      groups:
        - system:masters
  mapUsers: |
    - userarn: "arn:aws:iam::740781822140:user/saymon"
      username: "saymon"
      groups:
        - system:masters

